# -*- coding: utf-8 -*-
"""NeuralNetworks.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wIn8Z5VHWxQkbexoe8oNlE5mvCmawqG1
"""

import pandas
import numpy
import re
import nltk
import pickle
import joblib
from nltk.corpus import stopwords
nltk.download('stopwords')
from numpy import array
from keras.preprocessing.text import one_hot
from keras.preprocessing.sequence import pad_sequences
from keras.models import Sequential
from keras.layers.core import Activation, Dropout, Dense
from keras.layers import Flatten
from keras.layers import GlobalMaxPooling1D
from keras.layers import Conv1D
from keras.regularizers import l1
from keras.regularizers import l2
from keras.layers.embeddings import Embedding
from sklearn.model_selection import train_test_split
from keras.preprocessing.text import Tokenizer

from google.colab import drive
drive.mount('/content/drive')

"""Importing Dataset of Twitter Reviews"""

twitter_reviews = pandas.read_csv("/content/drive/My Drive/DATASET FOR ML ASSIGNMENT/IMDB Dataset.csv")
twitter_reviews.isnull().values.any()
print(twitter_reviews.head())

"""# Preprocessing Of Data"""

TAG_REMOVAL = re.compile(r'<[^>]+>')
def tags_removal(txt):
    return TAG_REMOVAL.sub('', txt)
    
def preprocess(sentence):
    sentence_of_words = tags_removal(sentence)
    sentence_of_words = re.sub('[^a-zA-Z]', ' ', sentence_of_words)
    sentence_of_words = re.sub(r'\s+[a-zA-Z]\s+', ' ', sentence_of_words)
    sentence_of_words = re.sub(r'\s+', ' ', sentence_of_words)
    return sentence_of_words

Y = twitter_reviews['sentiment']
Y = numpy.array(list(map(lambda x: 1 if x == 'positive' else 0, Y)))
sentences = list(twitter_reviews['review'])
X = []  
for sen in sentences:
    X.append(preprocess(sen))

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.20, random_state=42)

tokenizer = Tokenizer(num_words=5000)
tokenizer.fit_on_texts(X_train)
X_test = tokenizer.texts_to_sequences(X_test)
X_train = tokenizer.texts_to_sequences(X_train)

vocabsize = 1
vocabsize += len(tokenizer.word_index)
maxlength = 100
X_train = pad_sequences(X_train, padding='post', maxlen=maxlength)
X_test = pad_sequences(X_test, padding='post', maxlen=maxlength)

"""Using the GloVe precomputed Word Vectors"""

from numpy import array
from numpy import asarray
from numpy import zeros
glove_pretrained = open('/content/drive/My Drive/DATASET FOR ML ASSIGNMENT/glove.6B.100d.txt', encoding="utf8")
embeddings_dict = dict()

for line in glove_pretrained:
    sen = line.split()
    word = sen[0]
    vector = asarray(sen[1 : ], dtype='float32')
    embeddings_dict[word] = vector
glove_pretrained.close()

all_words = tokenizer.word_index.items()
embedding_matrix = zeros((vocabsize, 100))
for word, index in all_words:
    embedding_vector = embeddings_dict.get(word)
    if embedding_vector is not None:
        embedding_matrix[index]=embedding_vector

"""MLP + TRAIN EMBEDDING"""

model_mlp = Sequential()
embedding_layer = Embedding(vocabsize, 100, input_length=maxlength)
model_mlp.add(embedding_layer)
model_mlp.add(Flatten())
model_mlp.add(Dense(16, activation='sigmoid'))
model_mlp.add(Dense(1, activation='sigmoid'))
model_mlp.compile(optimizer='adam', loss='binary_crossentropy', metrics=['acc'])
print(model_mlp.summary())

history_mlp = model_mlp.fit(X_train, Y_train, batch_size=32000, epochs=100, verbose=1, validation_split=0.2)
score = model_mlp.evaluate(X_test, Y_test, verbose=1)
scoretrain = model_mlp.evaluate(X_train, Y_train, verbose=1)
print('Train Accuracy:', scoretrain[1])
print('Test Accuracy:', score[1])

"""MLP + GLOVE"""

model_mlp_glove = Sequential()
embedding_layer = Embedding(vocabsize, 100, weights=[embedding_matrix], input_length=maxlength, trainable=False)
model_mlp_glove.add(embedding_layer)
model_mlp_glove.add(Flatten())
model_mlp_glove.add(Dense(16, activation='sigmoid'))
model_mlp_glove.add(Dense(1, activation='sigmoid'))
model_mlp_glove.compile(optimizer='adam', loss='binary_crossentropy', metrics=['acc'])
print(model_mlp_glove.summary())

history_mlp_glove = model_mlp_glove.fit(X_train, Y_train, batch_size=32000, epochs=250, verbose=1, validation_split=0.2)
score = model_mlp_glove.evaluate(X_test, Y_test, verbose=1)
scoretrain = model_mlp_glove.evaluate(X_train, Y_train, verbose=1)
print('Train Accuracy:', scoretrain[1])
print('Test Accuracy:', score[1])

"""CNN + Trainable Embedding"""

model_cnn = Sequential()
embedding_layer = Embedding(vocabsize, 100, input_length=maxlength)
model_cnn.add(embedding_layer)
model_cnn.add(Conv1D(512, 5, activation='relu'))
model_cnn.add(GlobalMaxPooling1D())
model_cnn.add(Dense(16, activation='sigmoid'))
model_cnn.add(Dense(1, activation='sigmoid'))
model_cnn.compile(optimizer='adam', loss='binary_crossentropy', metrics=['acc'])
print(model_cnn.summary())

history_cnn = model_cnn.fit(X_train, Y_train, batch_size=16000, epochs=35, verbose=1, validation_split=0.2)
score = model_cnn.evaluate(X_test, Y_test, verbose=1)
scoretrain = model_cnn.evaluate(X_train, Y_train, verbose=1)
print('Train Accuracy:', scoretrain[1])
print('Test Accuracy:', score[1])

"""CNN + GloVe"""

model_cnn_glove = Sequential()
embedding_layer = Embedding(vocabsize, 100, weights=[embedding_matrix], input_length=maxlength, trainable=False)
model_cnn_glove.add(embedding_layer)
model_cnn_glove.add(Conv1D(512, 5, activation='relu'))
model_cnn_glove.add(GlobalMaxPooling1D())
model_cnn_glove.add(Dense(16, activation='sigmoid'))
model_cnn_glove.add(Dense(1, activation='sigmoid'))
model_cnn_glove.compile(optimizer='adam', loss='binary_crossentropy', metrics=['acc'])
print(model_cnn_glove.summary())

history_cnn_glove = model_cnn_glove.fit(X_train, Y_train, batch_size=16000, epochs=150, verbose=1, validation_split=0.2)
score = model_cnn_glove.evaluate(X_test, Y_test, verbose=1)
scoretrain = model_cnn_glove.evaluate(X_train, Y_train, verbose=1)
print('Train Accuracy:', scoretrain[1])
print('Test Accuracy:', score[1])

"""Model 
Pickling
"""

m1 = 'mlp' + '.joblib'
m2 = 'mlp_glove' + '.joblib'
m3 = 'cnn' + '.joblib'
m4 = 'cnn_glove' + '.joblib'
h1 = 'history_mlp' + '.joblib'
h2 = 'history_mlp_glove' + '.joblib'
h3 = 'history_cnn' + '.joblib'
h4 = 'history_cnn_glove' + '.joblib'

joblib.dump(model_mlp, m1)
joblib.dump(model_mlp_glove, m2)
joblib.dump(model_cnn, m3)
joblib.dump(model_cnn_glove, m4)
joblib.dump(history_mlp, h1)
joblib.dump(history_mlp_glove, h2)
joblib.dump(history_cnn, h3)
joblib.dump(history_cnn_glove, h4)

from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive
from google.colab import auth
from oauth2client.client import GoogleCredentials

# 1. Authenticate and create the PyDrive client.
auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)  

# get the folder id where you want to save your file
file = drive.CreateFile({'parents':[{u'id': '1rmTGbb19iJn6VbHoHdTYQbK0m0V_EQvP'}]})
file.SetContentFile(m1)
file.Upload() 

file = drive.CreateFile({'parents':[{u'id': '1rmTGbb19iJn6VbHoHdTYQbK0m0V_EQvP'}]})
file.SetContentFile(m2)
file.Upload() 

file = drive.CreateFile({'parents':[{u'id': '1rmTGbb19iJn6VbHoHdTYQbK0m0V_EQvP'}]})
file.SetContentFile(m3)
file.Upload() 

file = drive.CreateFile({'parents':[{u'id': '1rmTGbb19iJn6VbHoHdTYQbK0m0V_EQvP'}]})
file.SetContentFile(m4)
file.Upload() 

file = drive.CreateFile({'parents':[{u'id': '1rmTGbb19iJn6VbHoHdTYQbK0m0V_EQvP'}]})
file.SetContentFile(h1)
file.Upload() 

file = drive.CreateFile({'parents':[{u'id': '1rmTGbb19iJn6VbHoHdTYQbK0m0V_EQvP'}]})
file.SetContentFile(h2)
file.Upload()

file = drive.CreateFile({'parents':[{u'id': '1rmTGbb19iJn6VbHoHdTYQbK0m0V_EQvP'}]})
file.SetContentFile(h3)
file.Upload()

file = drive.CreateFile({'parents':[{u'id': '1rmTGbb19iJn6VbHoHdTYQbK0m0V_EQvP'}]})
file.SetContentFile(h4)
file.Upload()

# model_mlp = joblib.load('/content/drive/My Drive/DATASET FOR ML ASSIGNMENT/' + m1)
# model_mlp_glove = joblib.load('/content/drive/My Drive/DATASET FOR ML ASSIGNMENT/' + m2)
# model_cnn = joblib.load('/content/drive/My Drive/DATASET FOR ML ASSIGNMENT/' + m3)
# model_cnn_glove = joblib.load('/content/drive/My Drive/DATASET FOR ML ASSIGNMENT/' + m4)
# history_mlp = joblib.load('/content/drive/My Drive/DATASET FOR ML ASSIGNMENT/' + h1)
# history_mlp_glove = joblib.load('/content/drive/My Drive/DATASET FOR ML ASSIGNMENT/' + h2)
# history_cnn = joblib.load('/content/drive/My Drive/DATASET FOR ML ASSIGNMENT/' + h3)
# history_cnn_glove = joblib.load('/content/drive/My Drive/DATASET FOR ML ASSIGNMENT/' + h4)

"""# Plotting the Graphs"""

import matplotlib.pyplot as plt

"""NN + Self Trained Embedding Layer"""

plt.plot(list(range(1, 101)), history_mlp.history['val_loss'], color='green', label='Validation Loss')
plt.plot(list(range(1, 101)), history_mlp.history['loss'], color='brown', label='Training Loss')
plt.plot(list(range(1, 101)), history_mlp.history['val_acc'], color='indigo', label='Validation Accuracy')
plt.plot(list(range(1, 101)), history_mlp.history['acc'], color='orange', label='Training Accuracy')
plt.xlabel('Epoch')
plt.ylabel('Loss/Accuracy')
plt.title('Model Loss & Accuracy (NN with Self Training Embedding Layer)')
plt.legend(loc='best')
plt.show()

"""NN + GloVe"""

plt.plot(list(range(1, 251)), history_mlp_glove.history['val_loss'], color='green', label='Validation Loss')
plt.plot(list(range(1, 251)), history_mlp_glove.history['loss'], color='brown', label='Training Loss')
plt.plot(list(range(1, 251)), history_mlp_glove.history['val_acc'], color='indigo', label='Validation Accuracy')
plt.plot(list(range(1, 251)), history_mlp_glove.history['acc'], color='orange', label='Training Accuracy')
plt.xlabel('Epoch')
plt.ylabel('Loss/Accuracy')
plt.title('Model Loss & Accuracy (NN with GloVe Embedding Layer)')
plt.legend(loc='best')
plt.show()

"""CNN + Self Trained Embedding Layer"""

plt.plot(list(range(1, 36)), history_cnn.history['val_loss'], color='green', label='Validation Loss')
plt.plot(list(range(1, 36)), history_cnn.history['loss'], color='brown', label='Training Loss')
plt.plot(list(range(1, 36)), history_cnn.history['val_acc'], color='indigo', label='Validation Accuracy')
plt.plot(list(range(1, 36)), history_cnn.history['acc'], color='orange', label='Training Accuracy')
plt.xlabel('Epoch')
plt.ylabel('Loss/Accuracy')
plt.title('Model Loss & Accuracy (CNN with Self Training Embedding Layer)')
plt.legend(loc='best')
plt.show()

"""CNN + GloVe"""

plt.plot(list(range(1, 151)), history_cnn_glove.history['val_loss'], color='green', label='Validation Loss')
plt.plot(list(range(1, 151)), history_cnn_glove.history['loss'], color='brown', label='Training Loss')
plt.plot(list(range(1, 151)), history_cnn_glove.history['val_acc'], color='indigo', label='Validation Accuracy')
plt.plot(list(range(1, 151)), history_cnn_glove.history['acc'], color='orange', label='Training Accuracy')
plt.xlabel('Epoch')
plt.ylabel('Loss/Accuracy')
plt.title('Model Loss & Accuracy (CNN with GloVe Embedding Layer)')
plt.legend(loc='best')
plt.show()